name: itc_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  get: ^4.7.2
  get_it: ^8.0.3
  fpdart: ^1.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  project_structure_builder: ^0.0.2+1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/itc.png
    - assets/images/form.png
    - assets/images/quiz.png
    - assets/images/study.png
    - assets/images/other.png
    - assets/images/other.png
    - assets/images/course.png
    - assets/images/lecture.png
    - assets/images/batches.png
    - assets/images/project.png
    - assets/images/seminar.png
    - assets/images/autodesk.png
    - assets/images/hardware.jpg
    - assets/images/insights.png
    - assets/images/internship.jpg
    - assets/images/networking.png
    - assets/images/accounting.png
    - assets/images/multimedia.png
    - assets/images/attendance.png
    - assets/images/assignment.png
    - assets/images/itc_header.png
    - assets/images/programming.png
    - assets/images/artificial.webp
    - assets/images/examination.png
    - assets/images/student_list.png
    - assets/images/data_analytics.png
    - assets/images/spoken_english.png
    - assets/images/ethical_hacking.jpg
    
    - assets/user_credentials.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
